version: "3"

services:
  #digdagサーバー
  digdag_server:
    container_name: digdag_server
    build:
      context: .
      dockerfile: ./docker/digdag_server/dockerfile
    depends_on:
      - digdag_postgres
    volumes:
      - .:/workspace
      - ./docker/digdag_server:/opt/etc/digdag
    command: ["server", "-c", "/opt/etc/digdag/server.properties"]
    ports:
      - 8080:65432
    networks:
      - digdag_network

  #digdagクライアント(このコンテナでdigdagコマンドを使う)
  digdag_client:
    container_name: digdag_client
    build:
      context: .
      dockerfile: ./docker/digdag_client/dockerfile
    volumes:
      - .:/workspace
    ports:
      - 8081:65432
    tty: true
    depends_on:
      - digdag_server
    networks:
      - digdag_network

  #digdagのデータ保存用PostgreSQL
  digdag_postgres:
    image: postgres:14-alpine
    container_name: digdag_postgres
    ports:
      - 8082:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digdag_db
    networks:
      - digdag_network

  #dozzleサーバー(digdagサーバーのログ確認用)
  dozzle_server:
    container_name: dozzle_server
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:8080
    depends_on:
      - digdag_server
    networks:
      - digdag_network

networks:
  digdag_network:
    driver: bridge

volumes:
  db-store:
