FROM openjdk:11

RUN mkdir /workspace
WORKDIR /workspace

RUN curl -L "https://dl.digdag.io/digdag-latest" -o /usr/local/bin/digdag && \
    chmod +x /usr/local/bin/digdag && \
    apt-get update && apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/* && \
    curl -fsSL https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz \
    | tar -xzC /usr/local/bin --strip=1 docker/docker

ENTRYPOINT ["java", "-jar", "/usr/local/bin/digdag"]
